name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Release]

    steps:
    - uses: actions/checkout@v2
   
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3
   
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.1.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{ github.workspace }}/ext/'
        install-deps: 'true'
        modules: 'qtbase'

    - name: Download CURL
      working-directory: ${{github.workspace}}/ext
      run: cd ${{github.workspace}}/ext;
           curl.exe --output curl.zip https://curl.se/windows/dl-7.81.0/curl-7.81.0-win64-mingw.zip;
           tar -xvzf .\curl.zip;
           mv ./curl-7.81.0-win64-mingw ./curl;

    - name: Build ChollianWallpaper
      working-directory: ${{github.workspace}}
      run: mkdir build_${{matrix.build_type}}; 
           cd build_${{matrix.build_type}}; 
           cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCURL_LIBRARY=${{github.workspace}}/ext/curl/lib/libcurl.dll.a -DCURL_INCLUDE_DIR=${{github.workspace}}/ext/curl/include ..; 
           MSBuild.exe PACKAGE.vcxproj -p:Configuration=Release;
    
    - name: Upload a archived bundle
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: windows_installer_${{matrix.build_type}}
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{github.workspace}}/build_${{matrix.build_type}}/ChollianInstaller.exe


